about:
  home: 'https://github.com/kdmurray91/kWIP'
  summary: "kWIP implements a de novo, alignment free measure of sample genetic dissimilarity"

build:
  number: 0

source:
  git_url: https://github.com/kdmurray91/kWIP
  git_tag: 3cf8a9e8cd1183ed7ce7a4b5a14594a9d9112fd7

requirements:
  build:
    - zlib
    - cmake >= 2.8
    - gcc >= 4.8

extra:
  notes: |
    The k-mer Weighted Inner Product (kWIP) implements a de novo, alignment free measure of sample genetic dissimilarity which operates upon raw sequencing reads. It is able to calculate the genetic dissimilarity between samples without any reference genome, and without assembling one.


